---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  labels:
    gitops.tier.layer: applications
spec:
  sourceRepos: []  # Populated by kustomize patches in 3-apps/kustomization.yaml
  destinations:
  - namespace: ci
    server: '*'
  - namespace: dev
    server: '*'
  - namespace: staging
    server: '*'
  - namespace: prod
    server: '*'
  - namespace: tools
    server: '*'
  - namespace: ibm-common-services
    server: '*'
  - namespace: cloudpak
    server: '*'
  - namespace: openshift-gitops
    server: '*'
  clusterResourceWhitelist:
  # TODO: SCC needs to be moved to 1-infra, here for now pipeline sa for buildah
  - group: "security.openshift.io"
    kind: SecurityContextConstraints
  - group: "rbac.authorization.k8s.io"
    kind: ClusterRole
  - group: "rbac.authorization.k8s.io"
    kind: ClusterRoleBinding
  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to my-project
    policies:
    - p, proj:my-project:read-only, applications, get, my-project/*, allow
    groups:
    - argocd-admins
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications-set
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  labels:
    gitops.tier.layer: gitops
spec:
  generators:
  - list:
      elements:
      - cluster: prod-cluster
        url: https://kubernetes.default.svc
      - cluster: dr-cluster
        url: https://c111-e.us-east.containers.cloud.ibm.com:31784
  template:
    metadata:
      name: '{{cluster}}-applications'
    spec:
      project: applications
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        path: 3-apps
      destination:
        server: '{{url}}'
        namespace: openshift-gitops
